"""
settings.py -- QB SKU / Rate-Plan mapping backend
=================================================
Persists two files next to this module:

  sku_catalog.json      -- list of QB SKU objects discovered from invoice imports
  sku_mappings.json     -- list of {ratePlanCode, skuKey, defaultPrice, notes} rows

Endpoints:
  GET  /api/settings/sku-catalog              list all known SKUs
  POST /api/settings/sku-catalog              upsert a SKU (key, fullPath, defaultPrice)
  DELETE /api/settings/sku-catalog/{sku_key}  remove a SKU

  GET  /api/settings/sku-mappings             list rate-plan -> SKU mappings
  POST /api/settings/sku-mappings             upsert a mapping
  DELETE /api/settings/sku-mappings/{rate_plan_code}  remove a mapping

  GET  /api/settings/customer-overrides            list per-customer price overrides
  POST /api/settings/customer-overrides            upsert {customerName, skuKey, price}
  DELETE /api/settings/customer-overrides/{id}     remove override by id (customerName|skuKey)

  POST /api/settings/import-qb-skus           parse uploaded QB CSV -> populate sku_catalog
  GET  /api/settings/unmapped-rate-plans       rate plan codes seen in MyAdmin with no mapping
"""

from fastapi import APIRouter, HTTPException, UploadFile, File
from pydantic import BaseModel
from typing import Optional, Dict, List, Tuple
import csv
import io
import json
import os
import re
import time

router = APIRouter()

# --- Disk paths --------------------------------------------------------------
_HERE = os.path.dirname(os.path.abspath(__file__))
SKU_CATALOG_FILE        = os.path.join(_HERE, "sku_catalog.json")
SKU_MAPPINGS_FILE       = os.path.join(_HERE, "sku_mappings.json")
CUSTOMER_OVERRIDES_FILE = os.path.join(_HERE, "sku_customer_overrides.json")
MYADMIN_CACHE_FILE      = os.path.join(_HERE, "myadmin_cache.json")


def _load(path, default):
    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except FileNotFoundError:
        print(f"[settings] File not found: {path}")
        return default
    except json.JSONDecodeError as e:
        print(f"[settings] JSON decode error in {path}: {e}")
        return default
    except Exception as e:
        print(f"[settings] Unexpected error loading {path}: {e}")
        return default


def _save(path, data):
    tmp = path + ".tmp"
    try:
        with open(tmp, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
        os.replace(tmp, path)
        print(f"[settings] Saved {len(data)} items to {path}")
    except Exception as e:
        print(f"[settings] ERROR saving {path}: {e}")
        raise


# --- In-memory stores ---------------------------------------------------------
# These are loaded from disk on every read operation (GET endpoints) to avoid
# stale-cache issues when the JSON files are updated externally (e.g. after a
# git pull or a previous import before the process was restarted).
#
# Write operations (POST/DELETE/import) keep them in sync in memory too so that
# multiple writes in the same request cycle are consistent.
#
# For a local desktop app with <1000 items in each file, disk reads on every
# GET are effectively instant and far safer than module-level caching.

def _catalog()  -> list: return _load(SKU_CATALOG_FILE,        [])
def _overrides()-> list: return _load(CUSTOMER_OVERRIDES_FILE, [])
def _myadmin_cache() -> dict: return _load(MYADMIN_CACHE_FILE, {})


def _normalize_mapping(m: dict) -> dict:
    """
    Normalise a sku_mappings.json entry to the canonical schema:
      { ratePlanCode, skuKey, defaultPrice, notes }

    Handles two legacy schemas:
      Old (generated by the sync import):
        { id, promoCode, skuKey, label }
      New (written by upsert_mapping POST):
        { ratePlanCode, skuKey, defaultPrice, notes }
    """
    code = (m.get("ratePlanCode") or m.get("promoCode") or m.get("id") or "").strip().upper()
    return {
        "ratePlanCode": code,
        "skuKey":       m.get("skuKey") or "",
        "defaultPrice": float(m.get("defaultPrice") or 0),
        "notes":        m.get("notes") or m.get("label") or "",
    }


def _mappings() -> list:
    """Load sku_mappings.json and normalise every entry to the canonical schema.
    If any entry needed migration (old promoCode/id schema), re-save the file
    so the migration only happens once.
    """
    raw = _load(SKU_MAPPINGS_FILE, [])
    normalised = [_normalize_mapping(m) for m in raw]
    # Check whether any entry was in the old schema (has 'promoCode' or 'id' but no 'ratePlanCode')
    needs_migration = any("ratePlanCode" not in m for m in raw)
    if needs_migration and normalised:
        print(f"[settings] Migrating sku_mappings.json: "
              f"{len(normalised)} entries updated from promoCode->ratePlanCode schema")
        _save(SKU_MAPPINGS_FILE, normalised)
    return normalised

# Keep module-level references for write operations so imports/upserts
# don't need to reload from disk mid-operation.
sku_catalog:  list = _catalog()
sku_mappings: list = _mappings()
cust_ovr:     list = _overrides()

print(f"[settings] SKU catalog: {len(sku_catalog)} SKUs, "
      f"{len(sku_mappings)} mappings, {len(cust_ovr)} overrides")


# ================================================================================
#  SKU CATALOG
# ================================================================================

class SkuUpsert(BaseModel):
    skuKey: str
    fullPath: str
    defaultPrice: float = 0.0
    category: str = ""
    desc: str = ""
    cost: float = 0.0


@router.get("/settings/sku-catalog")
async def list_sku_catalog():
    # Always read from disk so stale in-memory state is never returned
    data = _catalog()
    return sorted(data, key=lambda x: x.get("skuKey", "").lower())


@router.post("/settings/sku-catalog")
async def upsert_sku(body: SkuUpsert):
    global sku_catalog
    sku_catalog = _catalog()   # reload from disk first
    existing = next((s for s in sku_catalog if s["skuKey"] == body.skuKey), None)
    if existing:
        existing.update(body.dict())
    else:
        sku_catalog.append(body.dict())
    _save(SKU_CATALOG_FILE, sku_catalog)
    return {"success": True, "sku": body.dict()}


@router.delete("/settings/sku-catalog/{sku_key:path}")
async def delete_sku(sku_key: str):
    global sku_catalog
    sku_catalog = _catalog()   # reload from disk first
    before = len(sku_catalog)
    sku_catalog = [s for s in sku_catalog if s["skuKey"] != sku_key]
    _save(SKU_CATALOG_FILE, sku_catalog)
    return {"success": True, "removed": before - len(sku_catalog)}


# ================================================================================
#  SKU MAPPINGS  (rate plan code -> QB SKU)
# ================================================================================

class MappingUpsert(BaseModel):
    ratePlanCode: str
    skuKey: str
    defaultPrice: float = 0.0
    notes: str = ""


@router.get("/settings/sku-mappings")
async def list_sku_mappings():
    data = _mappings()
    return sorted(data, key=lambda x: x.get("ratePlanCode", "").lower())


@router.post("/settings/sku-mappings")
async def upsert_mapping(body: MappingUpsert):
    global sku_mappings
    sku_mappings = _mappings()  # reload from disk first
    existing = next((m for m in sku_mappings if m["ratePlanCode"].upper() == body.ratePlanCode.upper()), None)
    data = body.dict()
    data["ratePlanCode"] = data["ratePlanCode"].upper()
    if existing:
        existing.update(data)
    else:
        sku_mappings.append(data)
    _save(SKU_MAPPINGS_FILE, sku_mappings)
    return {"success": True, "mapping": data}


@router.delete("/settings/sku-mappings/{rate_plan_code:path}")
async def delete_mapping(rate_plan_code: str):
    global sku_mappings
    sku_mappings = _mappings()  # reload from disk first
    before = len(sku_mappings)
    sku_mappings = [m for m in sku_mappings if m["ratePlanCode"].upper() != rate_plan_code.upper()]
    _save(SKU_MAPPINGS_FILE, sku_mappings)
    return {"success": True, "removed": before - len(sku_mappings)}


# ================================================================================
#  CUSTOMER PRICE OVERRIDES
# ================================================================================

class OverrideUpsert(BaseModel):
    customerName: str
    skuKey: str
    price: float


def _ovr_id(customer_name: str, sku_key: str) -> str:
    return f"{customer_name}|{sku_key}"


@router.get("/settings/customer-overrides")
async def list_overrides():
    data = _overrides()
    return sorted(data, key=lambda x: x.get("customerName", "").lower())


@router.post("/settings/customer-overrides")
async def upsert_override(body: OverrideUpsert):
    global cust_ovr
    cust_ovr = _overrides()    # reload from disk first
    oid = _ovr_id(body.customerName, body.skuKey)
    existing = next((o for o in cust_ovr if o["id"] == oid), None)
    data = {**body.dict(), "id": oid}
    if existing:
        existing.update(data)
    else:
        cust_ovr.append(data)
    _save(CUSTOMER_OVERRIDES_FILE, cust_ovr)
    return {"success": True, "override": data}


@router.delete("/settings/customer-overrides/{override_id:path}")
async def delete_override(override_id: str):
    global cust_ovr
    cust_ovr = _overrides()    # reload from disk first
    before = len(cust_ovr)
    cust_ovr = [o for o in cust_ovr if o["id"] != override_id]
    _save(CUSTOMER_OVERRIDES_FILE, cust_ovr)
    return {"success": True, "removed": before - len(cust_ovr)}


# ================================================================================
#  IMPORT QB INVOICE CSV  ->  populate sku_catalog (and customer overrides)
# ================================================================================

def _parse_item(item_str: str) -> Tuple[str, str, str]:
    """
    Parse a QB Item (col P) string into (group, sku_name, desc).

    Format:  'Geotab Service:Service Fee Geotab (HOS V2) (Service Fee Geotab (HOS))'
      group    = 'Geotab Service'           (text before first ':')
      sku_name = 'Service Fee Geotab (HOS V2)'  (after ':', strip last top-level parens)
      desc     = 'Service Fee Geotab (HOS)'     (content of that last top-level parens)

    Uses a right-to-left balanced-paren scan so nested parens inside SKU names
    (e.g. 'DM Service Fee (Periodic)') are preserved correctly.
    """
    item_str = item_str.strip()

    # Split off the group prefix
    if ':' in item_str:
        colon    = item_str.index(':')
        group    = item_str[:colon].strip()
        rest     = item_str[colon + 1:].strip()
    else:
        group = ''
        rest  = item_str

    desc     = ''
    sku_name = rest

    # Strip the last top-level (...) to get the clean SKU name
    if rest.endswith(')'):
        depth = 0
        i = len(rest) - 1
        while i >= 0:
            if rest[i] == ')':
                depth += 1
            elif rest[i] == '(':
                depth -= 1
                if depth == 0:
                    desc     = rest[i + 1:-1].strip()
                    sku_name = rest[:i].strip()
                    break
            i -= 1

    return group, sku_name, desc


def _parse_qb_csv(content: str) -> dict:
    """
    Parse QB invoice CSV (doubled-comma format).
    Col 5=Type, Col 13=Name, Col 15=Item (full QB path), Col 17=Qty, Col 19=Sales Price

    Returns {skus: {sku_name: {...}}, customers: {parent_name: {sku_name: price}}}
    """
    reader = csv.reader(io.StringIO(content))
    rows   = list(reader)

    skus_out:      dict = {}
    customers_out: dict = {}

    for row in rows:
        if len(row) <= 19:
            continue
        if row[5].strip() != 'Invoice':
            continue
        item_raw  = row[15].strip()
        name_raw  = row[13].strip()
        price_raw = row[19].strip()

        if not item_raw or not name_raw:
            continue
        if '%' in price_raw:
            continue

        try:
            price = float(price_raw)
        except ValueError:
            continue

        group, sku_name, desc = _parse_item(item_raw)

        if not sku_name:
            continue

        if sku_name not in skus_out:
            skus_out[sku_name] = {
                'skuKey':        sku_name,
                'fullPath':      item_raw,   # full col P value kept for reference
                'defaultPrice':  price,
                'category':      group,
                'desc':          desc,
                'prices':        set(),
                'customerCount': 0,
            }
        skus_out[sku_name]['prices'].add(price)
        skus_out[sku_name]['customerCount'] += 1

        # Parent customer name (strip child sub-account after ':')
        parent_name = name_raw.split(':')[0].strip()
        if parent_name not in customers_out:
            customers_out[parent_name] = {}
        customers_out[parent_name][sku_name] = price

    # Convert price sets to sorted lists
    for v in skus_out.values():
        v['prices'] = sorted(v['prices'])

    return {'skus': skus_out, 'customers': customers_out}


@router.post("/settings/import-qb-skus")
async def import_qb_skus(file: UploadFile = File(...)):
    """Upload a QB invoice CSV to auto-populate the SKU catalog and customer price overrides."""
    global sku_catalog, cust_ovr
    sku_catalog = _catalog()    # reload from disk before import
    cust_ovr    = _overrides()  # reload from disk before import

    content = (await file.read()).decode("utf-8-sig", errors="replace")
    parsed  = _parse_qb_csv(content)

    skus_added   = 0
    skus_updated = 0
    ovr_added    = 0
    ovr_updated  = 0

    # -- Upsert SKU catalog ----------------------------------------------------
    for sku_key, data in parsed['skus'].items():
        existing = next((s for s in sku_catalog if s['skuKey'] == sku_key), None)
        entry = {
            'skuKey':       data['skuKey'],
            'fullPath':     data['fullPath'],
            'defaultPrice': data['defaultPrice'],
            'category':     data['category'],
            'desc':         data.get('desc', ''),
        }
        if existing:
            existing.update(entry)
            skus_updated += 1
        else:
            sku_catalog.append(entry)
            skus_added += 1

    _save(SKU_CATALOG_FILE, sku_catalog)

    # -- Upsert customer price overrides --------------------------------------
    for cust_name, skus in parsed['customers'].items():
        for sku_key, price in skus.items():
            oid = _ovr_id(cust_name, sku_key)
            existing = next((o for o in cust_ovr if o['id'] == oid), None)
            data_row = {
                'id':           oid,
                'customerName': cust_name,
                'skuKey':       sku_key,
                'price':        price,
            }
            if existing:
                existing.update(data_row)
                ovr_updated += 1
            else:
                cust_ovr.append(data_row)
                ovr_added += 1

    _save(CUSTOMER_OVERRIDES_FILE, cust_ovr)

    return {
        "success":      True,
        "skusAdded":    skus_added,
        "skusUpdated":  skus_updated,
        "ovrAdded":     ovr_added,
        "ovrUpdated":   ovr_updated,
        "totalSkus":    len(sku_catalog),
        "totalCustomers": len(parsed['customers']),
    }


# ================================================================================
#  IMPORT ITEM PRICE LIST CSV  ->  fill $0 gaps + add new SKUs, never override
# ================================================================================

def _parse_price(s: str) -> Optional[float]:
    s = s.strip().replace(',', '')
    try:    return float(s)
    except: return None


def _parse_price_list_csv(content: str) -> List[dict]:
    """
    Parse a QB Item Price List CSV (doubled-comma format).
    Col 2 = Item (Group:SKU Name), Col 4 = Description, Col 6 = Cost, Col 8 = Price

    Skips parent/category rows (no ':' in Item column).
    Returns list of {skuKey, fullPath, category, desc, cost, defaultPrice}
    """
    reader = csv.reader(io.StringIO(content))
    rows   = list(reader)
    items  = []

    for row in rows[1:]:          # skip header
        if len(row) < 9:
            continue
        item_raw  = row[2].strip()
        desc_raw  = row[4].strip()
        cost_raw  = row[6].strip()
        price_raw = row[8].strip()

        if not item_raw or ':' not in item_raw:
            continue              # skip category parent rows

        price = _parse_price(price_raw)
        cost  = _parse_price(cost_raw)
        if price is None:
            continue

        colon    = item_raw.index(':')
        group    = item_raw[:colon].strip()
        sku_name = item_raw[colon + 1:].strip()
        if not sku_name:
            continue

        items.append({
            'skuKey':       sku_name,
            'fullPath':     item_raw,
            'category':     group,
            'desc':         desc_raw,
            'cost':         cost or 0.0,
            'defaultPrice': price,
        })

    return items


@router.post("/settings/import-price-list")
async def import_price_list(file: UploadFile = File(...)):
    """
    Upload a QB Item Price List CSV.

    Rules:
      - If SKU not in catalog -> ADD it (new SKU).
      - If SKU in catalog with defaultPrice == 0 -> UPDATE price (fill the gap).
      - If SKU in catalog with defaultPrice > 0  -> SKIP (never override
        customer-specific pricing derived from invoice imports).
    """
    global sku_catalog
    sku_catalog = _catalog()    # reload from disk before import

    content = (await file.read()).decode("utf-8-sig", errors="replace")
    items   = _parse_price_list_csv(content)

    if not items:
        raise HTTPException(status_code=400, detail="No valid items found in price list CSV.")

    catalog_index = {s['skuKey']: s for s in sku_catalog}

    added   = 0
    updated = 0
    skipped = 0

    for item in items:
        existing = catalog_index.get(item['skuKey'])
        if existing is None:
            # Brand-new SKU -- add to catalog
            new_entry = {
                'skuKey':       item['skuKey'],
                'fullPath':     item['fullPath'],
                'defaultPrice': item['defaultPrice'],
                'category':     item['category'],
                'desc':         item['desc'],
                'cost':         item['cost'],
            }
            sku_catalog.append(new_entry)
            catalog_index[item['skuKey']] = new_entry
            added += 1
        elif (existing.get('defaultPrice') or 0.0) == 0.0 and item['defaultPrice'] > 0:
            # Existing SKU with $0 price -- fill the gap
            existing['defaultPrice'] = item['defaultPrice']
            if item.get('cost'):
                existing['cost'] = item['cost']
            if not existing.get('desc') and item.get('desc'):
                existing['desc'] = item['desc']
            updated += 1
        else:
            # Existing SKU with a real price already -- do not touch
            skipped += 1

    sku_catalog.sort(key=lambda x: x.get('skuKey', '').lower())
    _save(SKU_CATALOG_FILE, sku_catalog)

    return {
        "success":    True,
        "added":      added,
        "updated":    updated,
        "skipped":    skipped,
        "totalItems": len(items),
        "totalSkus":  len(sku_catalog),
    }


# ================================================================================
#  UNMAPPED RATE PLANS  (rate plan codes in MyAdmin with no SKU mapping)
# ================================================================================

@router.get("/settings/unmapped-rate-plans")
async def get_unmapped_rate_plans():
    """
    Compare rate plan codes seen in the MyAdmin sync cache against sku_mappings.
    Reads myadmin_cache.json directly -- no import of customers module needed.
    """
    try:
        cache = _myadmin_cache()
        raw   = cache.get("raw_customers") or []
        if not raw:
            return {"unmapped": [], "total": 0, "hasCachedData": False}

        seen_codes: set = set()
        code_counts: dict = {}
        for c in raw:
            for d in (c.get("devices") or []):
                code = (d.get("promoCode") or "").strip().upper()
                if code:
                    seen_codes.add(code)
                    code_counts[code] = code_counts.get(code, 0) + 1

        mapped_codes = {m["ratePlanCode"].upper() for m in _mappings()}
        unmapped     = sorted(seen_codes - mapped_codes)

        return {
            "unmapped": [
                {"ratePlanCode": code, "deviceCount": code_counts.get(code, 0)}
                for code in unmapped
            ],
            "total":        len(unmapped),
            "hasCachedData": True,
        }
    except Exception as e:
        import traceback
        tb = traceback.format_exc()
        print(f"[settings] unmapped-rate-plans ERROR: {e}\n{tb}")
        return {"unmapped": [], "total": 0, "hasCachedData": False, "_error": str(e)}


# ================================================================================
#  SUMMARY  (for Settings page header cards)
# ================================================================================

@router.get("/settings/summary")
async def get_settings_summary():
    """
    Summary counts for the Settings page header cards.
    Reads myadmin_cache.json directly -- no import of customers module needed.
    """
    try:
        cache        = _myadmin_cache()
        raw          = cache.get("raw_customers") or []
        catalog_now  = _catalog()
        mappings_now = _mappings()
        overrides_now= _overrides()

        seen_codes: set = set()
        for c in raw:
            for d in (c.get("devices") or []):
                code = (d.get("promoCode") or "").strip().upper()
                if code:
                    seen_codes.add(code)

        mapped_codes   = {m["ratePlanCode"].upper() for m in mappings_now}
        unmapped_count = len(seen_codes - mapped_codes)

        return {
            "skuCount":      len(catalog_now),
            "mappingCount":  len(mappings_now),
            "overrideCount": len(overrides_now),
            "unmappedCount": unmapped_count,
            "hasCachedData": bool(raw),
        }
    except Exception as e:
        import traceback
        tb = traceback.format_exc()
        print(f"[settings] summary ERROR: {e}\n{tb}")
        # Return disk counts even on error so the page still shows data
        try:
            return {
                "skuCount":      len(_catalog()),
                "mappingCount":  len(_mappings()),
                "overrideCount": len(_overrides()),
                "unmappedCount": 0,
                "hasCachedData": False,
                "_error": str(e),
            }
        except Exception:
            return {"skuCount": 0, "mappingCount": 0, "overrideCount": 0,
                    "unmappedCount": 0, "hasCachedData": False, "_error": str(e)}


# ===============================================================================
#  DEBUG  (open in browser to diagnose file-path / content issues)
# ===============================================================================

@router.get("/settings/debug")
async def debug_settings():
    """Diagnostic endpoint -- open http://127.0.0.1:8001/api/settings/debug in browser."""
    def file_info(path):
        exists = os.path.exists(path)
        size   = os.path.getsize(path) if exists else 0
        # Try to load and count items
        try:
            with open(path, "r", encoding="utf-8") as f:
                content = f.read()
            data = json.loads(content)
            count = len(data)
            first = str(data[0])[:120] if data else "(empty list)"
            err   = None
        except FileNotFoundError:
            count = 0; first = None; err = "FileNotFoundError"; content = ""
        except json.JSONDecodeError as e:
            count = 0; first = None; err = f"JSONDecodeError: {e}"
        except Exception as e:
            count = 0; first = None; err = str(e)
        return {
            "path":    path,
            "exists":  exists,
            "bytes":   size,
            "count":   count,
            "first":   first,
            "error":   err,
            "preview": (content[:200] if exists else ""),
        }

    return {
        "version":   "schema-migration",   # git commit -- if you see this, new code is running
        "here":      _HERE,
        "cwd":       os.getcwd(),
        "catalog":   file_info(SKU_CATALOG_FILE),
        "mappings":  file_info(SKU_MAPPINGS_FILE),
        "overrides": file_info(CUSTOMER_OVERRIDES_FILE),
    }
